---
title: "About"
author: "Billy Koech"
date: "10/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About

Billy is a member of the Harvard SEAS Engineers Without Borders Chapter. Members of this student organization work on projects located in developing countries to provide engineering solutions to challenges faced by local communities. One of the projects in Kenya deal with the provision of clean portable water to the communities. In the summer of 2019, Billy travelled to Kenya with a team of 8 to collect data on water usage trends and needs in the community. That collected data is availble in an excel sheet [here](raw-data/survey_data.xlsx)

While in the community the team also collected geospatial data and created a google earth kmz map. The kmz file can be found [here](raw-data/map.kmz).

This project includes visualizations of this data from which inferences can be drawn on water needs and water utilizations trends in the community of Kibuon.